-- MySQL Script generated by MySQL Workbench
-- 08/02/19 11:11:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbBienestar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbBienestar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbBienestar` DEFAULT CHARACTER SET utf8 ;
USE `dbBienestar` ;

-- -----------------------------------------------------
-- Table `dbBienestar`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBienestar`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(25) NULL,
  `paterno` VARCHAR(25) NULL,
  `materno` VARCHAR(25) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `genero` VARCHAR(2) NULL,
  `correo` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbBienestar`.`carrerasProfesionals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBienestar`.`carrerasProfesionals` (
  `idCarreraProfesional` INT NOT NULL AUTO_INCREMENT,
  `nombreCarrera` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarreraProfesional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbBienestar`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBienestar`.`alumnos` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(25) NULL,
  `paterno` VARCHAR(25) NULL,
  `materno` VARCHAR(25) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `genero` VARCHAR(2) NULL,
  `correo` VARCHAR(45) NULL,
  `idCarreraProfesional` INT NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_Estudiantes_CarrerasProfesionals_idx` (`idCarreraProfesional` ASC),
  CONSTRAINT `fk_Estudiantes_CarrerasProfesionals`
    FOREIGN KEY (`idCarreraProfesional`)
    REFERENCES `dbBienestar`.`carrerasProfesionals` (`idCarreraProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbBienestar`.`OperacionBienestars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBienestar`.`OperacionBienestars` (
  `idOperacionBienestar` INT NOT NULL AUTO_INCREMENT,
  `nombreOperacion` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idOperacionBienestar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbBienestar`.`Usuarios_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBienestar`.`Usuarios_copy1` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(25) NULL,
  `paterno` VARCHAR(25) NULL,
  `materno` VARCHAR(25) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `genero` VARCHAR(2) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbBienestar`.`operacionEstudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBienestar`.`operacionEstudiante` (
  `idOperacionEstudiante` INT NOT NULL AUTO_INCREMENT,
  `idAlumno` INT NOT NULL,
  `idOperacionBienestar` INT NOT NULL,
  `fecha` DATE NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idOperacionEstudiante`, `idAlumno`, `idOperacionBienestar`),
  INDEX `fk_Estudiantes_has_OperacionBienestars_OperacionBienestars1_idx` (`idOperacionBienestar` ASC),
  INDEX `fk_Estudiantes_has_OperacionBienestars_Estudiantes1_idx` (`idAlumno` ASC),
  CONSTRAINT `fk_Estudiantes_has_OperacionBienestars_Estudiantes1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `dbBienestar`.`alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiantes_has_OperacionBienestars_OperacionBienestars1`
    FOREIGN KEY (`idOperacionBienestar`)
    REFERENCES `dbBienestar`.`OperacionBienestars` (`idOperacionBienestar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbBienestar`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbBienestar`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(25) NULL,
  `paterno` VARCHAR(25) NULL,
  `materno` VARCHAR(25) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `genero` VARCHAR(2) NULL,
  `correo` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
