-- MySQL Script generated by MySQL Workbench
-- 08/07/19 15:08:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema icyyqfkx_dbbienestar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema icyyqfkx_dbbienestar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `icyyqfkx_dbbienestar` DEFAULT CHARACTER SET utf8 ;
USE `icyyqfkx_dbbienestar` ;

-- -----------------------------------------------------
-- Table `icyyqfkx_dbbienestar`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `icyyqfkx_dbbienestar`.`roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icyyqfkx_dbbienestar`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `icyyqfkx_dbbienestar`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(25) NULL,
  `paterno` VARCHAR(25) NULL,
  `materno` VARCHAR(25) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `genero` VARCHAR(2) NULL,
  `correo` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `idRoles` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles1_idx` (`idRoles` ASC),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`idRoles`)
    REFERENCES `icyyqfkx_dbbienestar`.`roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icyyqfkx_dbbienestar`.`carreraProfesionals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `icyyqfkx_dbbienestar`.`carreraProfesionals` (
  `idCarreraProfesional` INT NOT NULL AUTO_INCREMENT,
  `nombreCarrera` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idCarreraProfesional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icyyqfkx_dbbienestar`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `icyyqfkx_dbbienestar`.`alumnos` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(25) NULL,
  `paterno` VARCHAR(25) NULL,
  `materno` VARCHAR(25) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `genero` VARCHAR(2) NULL,
  `correo` VARCHAR(45) NULL,
  `idCarreraProfesional` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_Estudiantes_CarrerasProfesionals_idx` (`idCarreraProfesional` ASC),
  CONSTRAINT `fk_Estudiantes_CarrerasProfesionals`
    FOREIGN KEY (`idCarreraProfesional`)
    REFERENCES `icyyqfkx_dbbienestar`.`carreraProfesionals` (`idCarreraProfesional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icyyqfkx_dbbienestar`.`OperacionBienestars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `icyyqfkx_dbbienestar`.`OperacionBienestars` (
  `idOperacionBienestar` INT NOT NULL AUTO_INCREMENT,
  `nombreOperacion` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idOperacionBienestar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icyyqfkx_dbbienestar`.`Usuarios_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `icyyqfkx_dbbienestar`.`Usuarios_copy1` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombre` VARCHAR(25) NULL,
  `paterno` VARCHAR(25) NULL,
  `materno` VARCHAR(25) NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `genero` VARCHAR(2) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icyyqfkx_dbbienestar`.`operacionEstudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `icyyqfkx_dbbienestar`.`operacionEstudiante` (
  `idOperacionEstudiante` INT NOT NULL AUTO_INCREMENT,
  `idAlumno` INT NOT NULL,
  `idOperacionBienestar` INT NOT NULL,
  `fechaInicio` DATE NULL,
  `fechaFin` DATE NULL,
  `observaciones` TEXT NULL,
  `diagnostico` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idOperacionEstudiante`, `idAlumno`, `idOperacionBienestar`),
  INDEX `fk_Estudiantes_has_OperacionBienestars_OperacionBienestars1_idx` (`idOperacionBienestar` ASC),
  INDEX `fk_Estudiantes_has_OperacionBienestars_Estudiantes1_idx` (`idAlumno` ASC),
  CONSTRAINT `fk_Estudiantes_has_OperacionBienestars_Estudiantes1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `icyyqfkx_dbbienestar`.`alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiantes_has_OperacionBienestars_OperacionBienestars1`
    FOREIGN KEY (`idOperacionBienestar`)
    REFERENCES `icyyqfkx_dbbienestar`.`OperacionBienestars` (`idOperacionBienestar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
